version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: aol_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 5000
      DB_NAME: aol_db
      DB_USER: postgres
      DB_PASSWORD: abc
      DB_HOST: postgres
      NODE_ENV: development
      JWT_SECRET: 47feaf8a812a57cab92f805756976ac632a3a3b23469b856eb2ffa4baf7d7379fb6fe290cb0e24b7f367d39a3312c14a99bd9ae26b6ef83db1ed651cb8f23968
      GOOGLE_CLIENT_ID: 147272879504-g4gjtddv5k69sp6f421s3540qcoiihad.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: 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
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: